name: my_pub
description: A Flutter application for ordering in a Pub.

dependencies:
  flutter:
    sdk: flutter
  intl:

  cupertino_icons:
  backdrop:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/my_pub_logo.png
    - assets/images/my_pub_icon.png
    - assets/images/coffee_mug.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaRegular.otf
          style: normal
        - asset: assets/fonts/HelveticaMedium.otf
          style: italic
          weight: 500
